pipeline {
    agent any

    environment {
        IMAGE_NAME = "project-service"
        IMAGE_TAG  = "1.0.${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                dir('project') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('project') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('project') {
                    sh "kubectl set image deployment/project-service project-service=${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
    }
}
