pipeline {
    agent any

    environment {
        IMAGE_NAME = "project-service"
        IMAGE_TAG  = "1.0.${BUILD_NUMBER}"  // Incremental version based on Jenkins build number
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                sh './mvnw clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                # Update the container image in the Deployment to the new version
                kubectl set image deployment/project-service \
                  project-service=${IMAGE_NAME}:${IMAGE_TAG} --record
                """
            }
        }
    }
}
